version: '3.8'
services:
    cfm_nginx:
        image: nginx:1.20.0-alpine
        container_name: cfm_nginx
        tty: true
        volumes:
            - ./:/var/www:ro
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports: 
            - 80:80
            - 443:443
        networks: 
            - cfm-network
        depends_on: 
            - cfm_php

    cfm_php:
        build:
            context: docker/php
        container_name: cfm_php
        volumes:
            - ./:/var/www:rw
        working_dir: /var/www
        networks: 
            - cfm-network
        depends_on:
            - cfm_mysql

    cfm_mysql:
        image: mysql:8.0.24
        container_name: cfm_mysql
        tty: true
        environment:
            MYSQL_DATABASE: company_financial_management
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: cfm
            MYSQL_PASSWORD: cfm
        ports: 
            - 3306:3306    
        volumes:
            - cfm_db:/var/lib/mysql:rw
        networks:
            - cfm-network
        
volumes:
    cfm_db:

networks:
    cfm-network:
        driver: bridge